spring:
  datasource:
    url: jdbc:mysql://prodplannerdb.mysql.database.azure.com:3306/prodplanner?useSSL=true
    username: mrprodplanner
    password: Fakultaet73
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect